default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vzakladke_development
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  encoding: unicode
  host: localhost
  pool: 5

test:
  <<: *default
  database: vzakladke__test
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  encoding: unicode
  host: localhost
  pool: 5

#production:
#  <<: *default
#  adapter: postgresql
#  host: 127.0.0.1
#  database: vzakladke
#  username: deployer
#  password:
#  encoding: unicode
#  pool: 5