USERNAME: 'denys'
PASSWORD: 'denuk96'
MAILUSER: 'thinkiny.ads@gmail.com'
MAILSPASS: 'gijvyheyirpkecho'
GOOGLE_MAPS_API_KEY: 'AIzaSyDaSUECXk7vEFyTqN6XajXccqTL3OU2XJY'
FACEBOOK_AP_ID: '896477487457872'
FACEBOOK_AP_SECRET: 'ee3f16ea877643c25cabcad19295c5c7'
GOOGLE_KEY: '731415562513-rqbsudpt68cekphdboim4j0sv0l496k4.apps.googleusercontent.com'
GOOGLE_SECRET: 'I_QdcWyHSUp1Bu8wkC1XKyrU'
SECRET_KEY_BASE: vEd3O/Xcwyf8cK8/21sg4GbM2u5Nr/cTitTFbuh616Y38dmg18bbZTMTDAUO+L6s3vSwP0TBUD+x151dNeK+fqtLopYpVX2sHkdkZ/mimORLEuxvcgDgZP9MndVxwMaw5s/3uh5h3n9twOkWjAn/xkY/GK+FYvQMEp2jz4iN2/Mcv4XjoMCDsawwgwXlOR30xkBrjBnAz/LxTsdauA9+eF5GflEpH/iUveAfXnJoo3YInYE7rrDt3FS+AHT0OrMoCWE7d4S+pXR345StnC9buRBM9O6+YNiull9ml3Q2d10CiW2zCENFTOy/rciJyaEQ36ltbsmV65jqkZJzDSN4x5n29MOuxW9xuskl8vs2pWgMr/YjmLa8qDStfl7+xqndMC1kEijptFSN2NI5h4aHxwLS728ZQ3ns7t1z--hmetYGo+NCetZJ1E--iiDF3XIpb/xCGM+TNPmckg==